### ISSUE TITLE
edge浏览器无法运行

### ISSUE THREAD

**Issue by 2523264065** [lony2003/weiban-tool#1]
麻烦问一下作者用的是什么浏览器，我使用edge浏览器会在主页停着无法运行，或者是在课程页面的话他会进入视频一秒然后刷新到课程页面，然后反复这样

**Comment by 2523264065** [comment]
Uploading b35dd68e26959671dabb00411090e459.mp4…

电脑不会录视频，还望作者见谅

**Comment by lony2003** [comment]
第二种情况是正常的，第一种情况的话应该是因为你把窗口最小化或者切到其他窗口了，这个是浏览器的限制，需要你把那个网页单独提出来成一个窗口然后不要最小化这个窗口

**Comment by lony2003** [comment]
我用的chome测试正常

**Comment by lony2003** [comment]
请参考 #2 。本 issue 已关闭
