### ISSUE TITLE
保持在主页一直刷新

### ISSUE THREAD

**Issue by johntime2005** [lony2003/weiban-tool#2]
https://github.com/fangkehou-team/weiban-tool/assets/58386430/9dcf292a-f751-48af-9a7c-589e904d4329

视频附上
使用环境为chrome加油猴beta，但是仍然无法运行

**Comment by lony2003** [comment]
hmmmmm, woc 你们学校真下狠呐一个任务里放一大堆视频可太行了。。。。那这个应该就是我逻辑上的问题了，我发布了一个新版本，你们可以试试。本issue已关闭。
