### ISSUE TITLE
希望作者能增加考试功能

### ISSUE THREAD

**Issue by MINHANGSHUAI** [lony2003/weiban-tool#3]
可以增加考试功能么

**Comment by lony2003** [comment]
理论可以，不过我没有题库，也没有合适的服务器，如果要做的话耗时耗钱，只我自己做我肯定不做，而且毕竟这里面的题都不是很难，而且网上都有，没必要自动做吧，也没有课程那个恶心的动画，点一点又花不了多少时间，有写代码的时间都够我做好几遍题了

**Comment by lony2003** [comment]
如果你想做的话你可以先从建题库，买服务器开始
