### ISSUE TITLE
大佬，2024年6月脚本失效了。

### ISSUE THREAD

**Issue by zhi-c** [lony2003/weiban-tool#4]
在学习界面弹出：报了啥错误ReferenceError: getQueryString is not defined

**Comment by lony2003** [comment]
你现在试试，我也不知道能不能用，毕竟我今年好像没有weiban，不过我觉得大概率是你浏览器或者油猴的问题，照理来说应该不太可能出现这个问题

**Comment by lony2003** [comment]
去greasyfork更新到0.8.2版，如果没有提示你更新告诉我一声

**Comment by zhi-c** [comment]
更新了新的0.8.2版本还是出现问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月6日(星期四) 下午3:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fangkehou-team/weiban-tool] 大佬，2024年6月脚本失效了。 (Issue #4)














 
0.8.2版，如果没有提示你更新告诉我一声

**Comment by lony2003** [comment]
还是一样的问题吗

**Comment by zhi-c** [comment]
对的

**Comment by lony2003** [comment]
你浏览器是什么，试过Chrome了吗？主要是我现在也不知道你的问题到底是什么，你可以给F12控制台截个图我看一看

**Comment by ussop-ykf** [comment]
![image](https://github.com/fangkehou-team/weiban-tool/assets/71281953/367a90e8-5e59-4a88-93b4-34596bc48bbc)
你好，这是控制台的截图

**Comment by zhi-c** [comment]
![1015c4ff-18fd-4794-9646-d3800f9c2925](https://github.com/fangkehou-team/weiban-tool/assets/78789636/01460256-6d32-4644-bfc0-afe110901d22)
这个是用Edge浏览器，Chrome浏览器脚本没有运行成功。

**Comment by clairo-77** [comment]
哥，chrome我下载了打不开,显示无法访问此网页。然后脚本在edge火狐360急速都运行不了，显示有错误，我根据你评论区的大哥给的改法改了一下脚本然后第104行显示有错误，主页上点脚本也运行不了，哥，救命。

**Comment by lony2003** [comment]
问题已解决，安装0.8.3版本即可正常运行，但安全微伴现已引入验证码机制，本项目自此进入归档状态。

**Comment by lony2003** [comment]
详情请参见README以及脚本主页。
